---
title: "Time series analysis in R using xts"
author: "Artemiy Tumanyants"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!requireNamespace("xts"))
  install.packages('xts')
```


## Load xts package and download the data

```{r}
library(xts)

if(!file.exists('data.csv')){
download.file('https://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv',
                      'data.csv')
}
data <- read.csv('data.csv')

data$date <- as.Date.character(data$date)
```

## Filter the data

```{r}
filtered_data <- data[which(data$country_region == 'United Kingdom' & 
                              data$sub_region_1 == 'Greater London'),]

colnames(filtered_data)[9:14] <- gsub("_percent_change_from_baseline",
                                      "",
                                      colnames(filtered_data)[9:14])
```

```{r}
xts_data <- as.xts(filtered_data[,which(colnames(filtered_data) == 'retail_and_recreation'):
                          which(colnames(filtered_data) == 'residential')],
                   order.by = filtered_data$date)

xts_data <- xts_data['2020-06-01/']
xts_data <- na.omit(xts_data)
head(xts_data)
```

## Plot the data

```{r}
plot(xts_data,legend.loc = 'topright')
```


## Tidy the data more

```{r}
daily_median <- xts()
for (i in 1:6){
  daily_median <- merge.xts(daily_median, apply.daily(xts_data[,i],median))
}
plot(daily_median, legend.loc = 'topright')
```

## Apply 7-day smoothing

```{r}
smooth_data <- rollmean(daily_median,k=7,fill = NA)
plot(smooth_data,legend.loc = 'topright', main = 'Rolling mean')
```


